// Code generated by protoc-gen-go. DO NOT EDIT.
// source: write.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
/// message 对应生成代码的 struct
/// 定义客户端请求的数据格式
type ClientRequest struct {
	Item                 *Profile `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Index                string   `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	ElkType              string   `protobuf:"bytes,3,opt,name=elkType,proto3" json:"elkType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequest) Reset()         { *m = ClientRequest{} }
func (m *ClientRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequest) ProtoMessage()    {}
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67966b2b12a73214, []int{0}
}

func (m *ClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequest.Unmarshal(m, b)
}
func (m *ClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequest.Merge(m, src)
}
func (m *ClientRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequest.Size(m)
}
func (m *ClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequest proto.InternalMessageInfo

func (m *ClientRequest) GetItem() *Profile {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ClientRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ClientRequest) GetElkType() string {
	if m != nil {
		return m.ElkType
	}
	return ""
}

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Province             string   `protobuf:"bytes,2,opt,name=Province,proto3" json:"Province,omitempty"`
	Age                  string   `protobuf:"bytes,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Constellation        string   `protobuf:"bytes,4,opt,name=Constellation,proto3" json:"Constellation,omitempty"`
	MarriedOrNot         string   `protobuf:"bytes,5,opt,name=MarriedOrNot,proto3" json:"MarriedOrNot,omitempty"`
	Height               string   `protobuf:"bytes,6,opt,name=Height,proto3" json:"Height,omitempty"`
	Profession           string   `protobuf:"bytes,7,opt,name=Profession,proto3" json:"Profession,omitempty"`
	Weight               string   `protobuf:"bytes,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	WorkPlace            string   `protobuf:"bytes,9,opt,name=WorkPlace,proto3" json:"WorkPlace,omitempty"`
	Income               string   `protobuf:"bytes,10,opt,name=Income,proto3" json:"Income,omitempty"`
	DegreeOfEducation    string   `protobuf:"bytes,11,opt,name=DegreeOfEducation,proto3" json:"DegreeOfEducation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_67966b2b12a73214, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Profile) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *Profile) GetConstellation() string {
	if m != nil {
		return m.Constellation
	}
	return ""
}

func (m *Profile) GetMarriedOrNot() string {
	if m != nil {
		return m.MarriedOrNot
	}
	return ""
}

func (m *Profile) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *Profile) GetProfession() string {
	if m != nil {
		return m.Profession
	}
	return ""
}

func (m *Profile) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *Profile) GetWorkPlace() string {
	if m != nil {
		return m.WorkPlace
	}
	return ""
}

func (m *Profile) GetIncome() string {
	if m != nil {
		return m.Income
	}
	return ""
}

func (m *Profile) GetDegreeOfEducation() string {
	if m != nil {
		return m.DegreeOfEducation
	}
	return ""
}

// 定义服务端响应的数据格式
type ClientResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResponse) Reset()         { *m = ClientResponse{} }
func (m *ClientResponse) String() string { return proto.CompactTextString(m) }
func (*ClientResponse) ProtoMessage()    {}
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67966b2b12a73214, []int{2}
}

func (m *ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponse.Unmarshal(m, b)
}
func (m *ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponse.Marshal(b, m, deterministic)
}
func (m *ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponse.Merge(m, src)
}
func (m *ClientResponse) XXX_Size() int {
	return xxx_messageInfo_ClientResponse.Size(m)
}
func (m *ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponse proto.InternalMessageInfo

func (m *ClientResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientRequest)(nil), "proto.ClientRequest")
	proto.RegisterType((*Profile)(nil), "proto.Profile")
	proto.RegisterType((*ClientResponse)(nil), "proto.ClientResponse")
}

func init() { proto.RegisterFile("write.proto", fileDescriptor_67966b2b12a73214) }

var fileDescriptor_67966b2b12a73214 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x4f, 0x02, 0x31,
	0x14, 0x94, 0x6f, 0xf6, 0xf1, 0x11, 0x7d, 0x41, 0xd3, 0x10, 0x63, 0xc8, 0xc6, 0x18, 0x0e, 0x86,
	0x03, 0xde, 0xbc, 0x19, 0x34, 0x7e, 0x24, 0x02, 0x59, 0x4d, 0x38, 0xaf, 0xcb, 0x03, 0x1b, 0x96,
	0x76, 0xed, 0x16, 0x94, 0x9f, 0xe8, 0xbf, 0x32, 0x6d, 0x17, 0x15, 0x3d, 0xf5, 0xcd, 0xcc, 0x9b,
	0x49, 0xdb, 0x81, 0xda, 0xbb, 0xe2, 0x9a, 0x7a, 0x89, 0x92, 0x5a, 0x62, 0xc9, 0x1e, 0x7e, 0x04,
	0x8d, 0x41, 0xcc, 0x49, 0xe8, 0x80, 0xde, 0x56, 0x94, 0x6a, 0xf4, 0xa1, 0xc8, 0x35, 0x2d, 0x59,
	0xae, 0x93, 0xeb, 0xd6, 0xfa, 0x4d, 0xb7, 0xdd, 0x1b, 0x2b, 0x39, 0xe3, 0x31, 0x05, 0x56, 0xc3,
	0x16, 0x94, 0xb8, 0x98, 0xd2, 0x07, 0xcb, 0x77, 0x72, 0x5d, 0x2f, 0x70, 0x00, 0x19, 0x54, 0x28,
	0x5e, 0x3c, 0x6f, 0x12, 0x62, 0x05, 0xcb, 0x6f, 0xa1, 0xff, 0x99, 0x87, 0x4a, 0x96, 0x80, 0x08,
	0xc5, 0x61, 0xb8, 0x24, 0x9b, 0xef, 0x05, 0x76, 0xc6, 0x36, 0x54, 0xc7, 0x4a, 0xae, 0xb9, 0x88,
	0x28, 0x8b, 0xfc, 0xc6, 0xb8, 0x0f, 0x85, 0xab, 0xf9, 0x36, 0xd1, 0x8c, 0x78, 0x0a, 0x8d, 0x81,
	0x14, 0xa9, 0xa6, 0x38, 0x0e, 0x35, 0x97, 0x82, 0x15, 0xad, 0xb6, 0x4b, 0xa2, 0x0f, 0xf5, 0xc7,
	0x50, 0x29, 0x4e, 0xd3, 0x91, 0x1a, 0x4a, 0xcd, 0x4a, 0x76, 0x69, 0x87, 0xc3, 0x23, 0x28, 0xdf,
	0x11, 0x9f, 0xbf, 0x6a, 0x56, 0xb6, 0x6a, 0x86, 0xf0, 0x04, 0xc0, 0x5c, 0x97, 0xd2, 0xd4, 0xc4,
	0x57, 0xac, 0xf6, 0x8b, 0x31, 0xbe, 0x89, 0xf3, 0x55, 0x9d, 0xcf, 0x21, 0x3c, 0x06, 0x6f, 0x22,
	0xd5, 0x62, 0x1c, 0x87, 0x11, 0x31, 0xcf, 0x4a, 0x3f, 0x84, 0x71, 0xdd, 0x8b, 0x48, 0x2e, 0x89,
	0x81, 0x73, 0x39, 0x84, 0xe7, 0x70, 0x70, 0x4d, 0x73, 0x45, 0x34, 0x9a, 0xdd, 0x4c, 0x57, 0x91,
	0x7b, 0x53, 0xcd, 0xae, 0xfc, 0x17, 0xfc, 0x33, 0x68, 0x6e, 0x0b, 0x4b, 0x13, 0x29, 0x52, 0x32,
	0x6d, 0x28, 0x4a, 0xe2, 0x4d, 0xf6, 0xa5, 0x0e, 0xf4, 0x1f, 0xa0, 0x3e, 0x31, 0x75, 0x3f, 0x91,
	0x5a, 0xf3, 0x88, 0xf0, 0x12, 0xbc, 0x5b, 0x95, 0x44, 0x96, 0xc3, 0x56, 0x56, 0xeb, 0x4e, 0xf5,
	0xed, 0xc3, 0x3f, 0xac, 0xcb, 0xf7, 0xf7, 0x5e, 0xca, 0x96, 0xbf, 0xf8, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xc3, 0x83, 0x7d, 0x54, 0x41, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WriteServiceClient is the client API for WriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WriteServiceClient interface {
	// rpc 定义服务内的 GrpcWrite 远程调用
	GrpcWrite(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error)
}

type writeServiceClient struct {
	cc *grpc.ClientConn
}

func NewWriteServiceClient(cc *grpc.ClientConn) WriteServiceClient {
	return &writeServiceClient{cc}
}

func (c *writeServiceClient) GrpcWrite(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, "/proto.WriteService/GrpcWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WriteServiceServer is the server API for WriteService service.
type WriteServiceServer interface {
	// rpc 定义服务内的 GrpcWrite 远程调用
	GrpcWrite(context.Context, *ClientRequest) (*ClientResponse, error)
}

// UnimplementedWriteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWriteServiceServer struct {
}

func (*UnimplementedWriteServiceServer) GrpcWrite(ctx context.Context, req *ClientRequest) (*ClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcWrite not implemented")
}

func RegisterWriteServiceServer(s *grpc.Server, srv WriteServiceServer) {
	s.RegisterService(&_WriteService_serviceDesc, srv)
}

func _WriteService_GrpcWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WriteServiceServer).GrpcWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WriteService/GrpcWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WriteServiceServer).GrpcWrite(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WriteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WriteService",
	HandlerType: (*WriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcWrite",
			Handler:    _WriteService_GrpcWrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "write.proto",
}
